authentication: "authentication:3100"
authentication_login: "/v1/user/login"
authentication_signup: "/v1/user/signup"
authentication_renew: "/v1/token/renew"
user_management: "user-management:3200"
user_management_login: "/v1/login"
user_management_signup: "/v1/signup"
