name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H.%M')"
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build participant-api Docker image
      run: docker build . --file build/docker/participant-api/Dockerfile --tag infectieradarbe/participant-api-image:${{ steps.date.outputs.date }}
    - name: Build management-api Docker image
      run: docker build . --file build/docker/management-api/Dockerfile --tag infectieradarbe/management-api-image:${{ steps.date.outputs.date }}
    - name: Push participant-api Docker image
      run: docker push infectieradarbe/participant-api-image:${{ steps.date.outputs.date }}
    - name: Push management-api Docker image
      run: docker push infectieradarbe/management-api-image:${{ steps.date.outputs.date }}
